//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public CompanyDetail()
        {
            this.LogCompanyDetails = new HashSet<LogCompanyDetail>();
        }
    
        public long COD_Id { get; set; }
        public Nullable<long> COD_CMP_Id { get; set; }
        public string COD_PointOfContact { get; set; }
        public string COD_JobTitle { get; set; }
        public string COD_SSN { get; set; }
        public string COD_Address1 { get; set; }
        public string COD_Addr1City { get; set; }
        public Nullable<int> COD_Addr1StateId { get; set; }
        public Nullable<int> COD_Addr1CountryId { get; set; }
        public string COD_Address2 { get; set; }
        public string COD_Addr2City { get; set; }
        public Nullable<int> COD_Addr2StateId { get; set; }
        public Nullable<int> COD_Addr2CountryId { get; set; }
        public string COD_Phone1 { get; set; }
        public string COD_Phone2 { get; set; }
        public string COD_Email { get; set; }
        public string COD_Website { get; set; }
        public string COD_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<LogCompanyDetail> LogCompanyDetails { get; set; }
    }
}
