//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eFleetVehicleInspectionLog
    {
        public long InspectionLogID { get; set; }
        public long VehicleID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PreInspection { get; set; }
        public string PostInspection { get; set; }
        public long LocationId { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual eFleetVehicle eFleetVehicle { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
