//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInsurance
    {
        public long LINS_Id { get; set; }
        public long LINS_INS_Id { get; set; }
        public long LINS_CMP_Id { get; set; }
        public string LINS_IncuranceCarrier { get; set; }
        public string LINS_PolicyNumber { get; set; }
        public System.DateTime LINS_ExpirationDate { get; set; }
        public string LINS_InsuranceDocument { get; set; }
        public long LINS_ModifiedBy { get; set; }
        public System.DateTime LINS_ModifiedOn { get; set; }
        public Nullable<long> LINS_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LINS_ApprovedOn { get; set; }
        public string LINS_Comment { get; set; }
        public string LINS_IsApprove { get; set; }
        public string LINS_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Insurance Insurance { get; set; }
    }
}
