//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPreBill
    {
        public long LPBL_Id { get; set; }
        public long LPBL_PBL_Id { get; set; }
        public long LPBL_LocationId { get; set; }
        public Nullable<long> LPBL_CMP_Id { get; set; }
        public string LPBL_Discription { get; set; }
        public Nullable<decimal> LPBL_InvoiceAmount { get; set; }
        public Nullable<System.DateTime> LPBL_InvoiceDate { get; set; }
        public string LPBL_InvoiceDocument { get; set; }
        public long LPBL_ModifiedBy { get; set; }
        public System.DateTime LPBL_ModifiedOn { get; set; }
        public Nullable<long> LPBL_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LPBL_ApprovedOn { get; set; }
        public string LPBL_Comment { get; set; }
        public string LPBL_IsApprove { get; set; }
        public string LPBL_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual PreBillNumber PreBillNumber { get; set; }
    }
}
