//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreBill
    {
        public long PBL_Id { get; set; }
        public long PBL_LocationId { get; set; }
        public Nullable<long> PBL_CMP_Id { get; set; }
        public string PBL_Discription { get; set; }
        public Nullable<decimal> PBL_InvoiceAmount { get; set; }
        public Nullable<System.DateTime> PBL_InvoiceDate { get; set; }
        public string PBL_InvoiceDocument { get; set; }
        public string PBL_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual PreBillNumber PreBillNumber { get; set; }
    }
}
