//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetPOList_Result4
    {
        public Nullable<long> LPOD_Id { get; set; }
        public Nullable<long> LPOD_POD_Id { get; set; }
        public Nullable<System.DateTime> LPOD_PODate { get; set; }
        public Nullable<decimal> LPOD_POAmount { get; set; }
        public string LocationName { get; set; }
        public string POT_POType { get; set; }
        public string CMP_NameLegal { get; set; }
        public Nullable<System.DateTime> LPOD_DeliveryDate { get; set; }
        public string PO_Status { get; set; }
        public Nullable<long> LPOD_ApprovedBy { get; set; }
    }
}
