//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCategory
    {
        public long ACC_Id { get; set; }
        public string ACC_AccountCategory { get; set; }
        public string ACC_AccountDetailCategory { get; set; }
        public string ACC_IsActive { get; set; }
    }
}
