//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicantAcadmicDetail
    {
        public long AAD_Id { get; set; }
        public Nullable<long> AAD_APT_ApplicantId { get; set; }
        public string AAD_EducationType { get; set; }
        public string AAD_InstituteName { get; set; }
        public Nullable<System.DateTime> AAD_AttendedFrom { get; set; }
        public Nullable<System.DateTime> AAD_AttendedTo { get; set; }
        public string AAD_City { get; set; }
        public string AAD_State { get; set; }
        public Nullable<int> AAD_Zip { get; set; }
        public Nullable<System.DateTime> AAD_Date { get; set; }
        public string AAD_IsActive { get; set; }
        public string AAD_Address { get; set; }
    }
}
