//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantBackgroundHistory
    {
        public long ABH_Id { get; set; }
        public Nullable<long> ABH_APT_ApplicantId { get; set; }
        public string ABH_CompanyName { get; set; }
        public string ABH_Address { get; set; }
        public string ABH_City { get; set; }
        public string ABH_State { get; set; }
        public Nullable<int> ABH_ZIPCode { get; set; }
        public Nullable<long> ABH_Phone { get; set; }
        public string ABH_StillEmployed { get; set; }
        public string ABH_ReasonforLeaving { get; set; }
        public string ABH_ReasonForGAP { get; set; }
        public string ABH_SubToFedralMotor { get; set; }
        public string ABH_SafetySensitiveFunction { get; set; }
        public Nullable<System.DateTime> ABH_Date { get; set; }
        public string ABH_IsActive { get; set; }
    }
}
