//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public long APT_ApplicantId { get; set; }
        public Nullable<long> APT_ALA_UserId { get; set; }
        public Nullable<long> APT_JobPostingId { get; set; }
        public string APT_Status { get; set; }
        public Nullable<System.DateTime> APT_Date { get; set; }
        public string APT_IsActive { get; set; }
    }
}
