//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantLicenseHeald
    {
        public long ALH_Id { get; set; }
        public Nullable<long> ALH_APT_ApplicantId { get; set; }
        public string ALH_State { get; set; }
        public string ALH_LicenceNumber { get; set; }
        public string ALH_LicenseType { get; set; }
        public Nullable<System.DateTime> ALH_IssueDate { get; set; }
        public Nullable<System.DateTime> ALH_ExpirationDate { get; set; }
        public Nullable<System.DateTime> ALH_Date { get; set; }
        public string ALH_IsActive { get; set; }
    }
}
