//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantPersonalInfo
    {
        public long API_Id { get; set; }
        public Nullable<long> API_APT_ApplicantId { get; set; }
        public string API_FirstName { get; set; }
        public string API_MidName { get; set; }
        public string API_LastName { get; set; }
        public string API_Resume { get; set; }
        public string API_SSN { get; set; }
        public string API_DLNumber { get; set; }
        public Nullable<decimal> API_DesireSalaryWages { get; set; }
        public Nullable<System.DateTime> API_Date { get; set; }
        public string API_IsActive { get; set; }
        public string API_Title { get; set; }
    }
}
