//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantLoginAccess1
    {
        public long ALA_UserId { get; set; }
        public string ALA_LiginId { get; set; }
        public string ALA_Password { get; set; }
        public string ALA_FirstName { get; set; }
        public string ALA_MidName { get; set; }
        public string ALA_LastName { get; set; }
        public string ALA_eMailId { get; set; }
        public string ALA_Question { get; set; }
        public string ALA_Answer { get; set; }
        public Nullable<System.DateTime> ALA_Date { get; set; }
        public string ALA_IsActive { get; set; }
    }
}
