//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAccidentRecord
    {
        public long AAR_Id { get; set; }
        public Nullable<long> AAR_APT_ApplicantId { get; set; }
        public Nullable<System.DateTime> AAR_AccidantDate { get; set; }
        public string AAR_Discription { get; set; }
        public Nullable<int> AAR_NumberOfFatalities { get; set; }
        public Nullable<int> AAR_NumberOfInjuries { get; set; }
        public Nullable<System.DateTime> AAR_Date { get; set; }
        public string AAR_IsActive { get; set; }
    }
}
