//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestion
    {
        public long ASQ_Id { get; set; }
        public string ASQ_AssessmentType { get; set; }
        public string ASQ_QuestionType { get; set; }
        public string ASQ_Question { get; set; }
        public Nullable<System.DateTime> ASQ_Date { get; set; }
        public string ASQ_IsActive { get; set; }
    }
}
