//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.LogBills = new HashSet<LogBill>();
        }
    
        public long BLL_Id { get; set; }
        public long BLL_QBKId { get; set; }
        public Nullable<long> BLL_POD_Id { get; set; }
        public Nullable<long> BLL_MIS_Id { get; set; }
        public Nullable<long> BLL_PBL_Id { get; set; }
        public Nullable<long> BLL_CMP_Id { get; set; }
        public long BLL_LocationId { get; set; }
        public string BLL_BillType { get; set; }
        public Nullable<decimal> BLL_PoMisBdaAmount { get; set; }
        public Nullable<decimal> BLL_InvoiceAmount { get; set; }
        public Nullable<System.DateTime> BLL_InvoiceDate { get; set; }
        public string BLL_InvoiceDocument { get; set; }
        public string BLL_IsActive { get; set; }
    
        public virtual ICollection<LogBill> LogBills { get; set; }
        public virtual Company Company { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
