//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillFacilityItem
    {
        public long BFI_Id { get; set; }
        public long BFI_PBL_Id { get; set; }
        public long BFI_CFM_Id { get; set; }
        public Nullable<long> BFI_Unit { get; set; }
        public Nullable<decimal> BFI_Rate { get; set; }
        public string BFI_IsActive { get; set; }
    
        public virtual PreBillNumber PreBillNumber { get; set; }
        public virtual CompanyFacilityMapping CompanyFacilityMapping { get; set; }
    }
}
