//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSlotTime
    {
        public long BST_Id { get; set; }
        public string BST_EMP_EmployeeID { get; set; }
        public System.DateTime BST_SlotDate { get; set; }
        public long BST_SLT_Id { get; set; }
        public string BST_Status { get; set; }
        public Nullable<System.DateTime> BST_Date { get; set; }
        public string BST_IsActive { get; set; }
        public string BST_Title { get; set; }
    }
}
