//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetCostCodeMapping
    {
        public long BCM_Id { get; set; }
        public long BCM_CLM_Id { get; set; }
        public Nullable<decimal> BCM_BudgetPercent { get; set; }
        public Nullable<decimal> BCM_BudgetAmount { get; set; }
        public Nullable<decimal> BCM_BalanceAmount { get; set; }
        public int BCM_BudgetYear { get; set; }
        public System.DateTime BCM_Date { get; set; }
        public string BCM_BudgetStatus { get; set; }
        public string BCM_IsActive { get; set; }
        public Nullable<long> BCM_CLM_TransferId { get; set; }
        public string BCM_TransactionType { get; set; }
        public string BCM_BudgetSource { get; set; }
    
        public virtual CostCodeLocationMapping CostCodeLocationMapping { get; set; }
        public virtual CostCodeLocationMapping CostCodeLocationMapping1 { get; set; }
    }
}
