//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeMaster
    {
        public long CHK_Id { get; set; }
        public Nullable<long> CHK_CMP_Id { get; set; }
        public Nullable<long> CHK_CAD_AccId { get; set; }
        public Nullable<long> CHK_StartingFrom { get; set; }
        public Nullable<long> CHK_EndingFrom { get; set; }
        public Nullable<System.DateTime> CHK_CreatedDate { get; set; }
    }
}
