//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizenship
    {
        public long CTZ_Id { get; set; }
        public string CTZ_Citizenship { get; set; }
        public string CTZ_EMP_EmployeeID { get; set; }
        public string CTZ_lawfulResident { get; set; }
        public string CTZ_AlienRegisteationNumber { get; set; }
        public string CTZ_FormI94 { get; set; }
        public string CTZ_ForeignPassport { get; set; }
        public Nullable<System.DateTime> CTZ_Date { get; set; }
        public string CTZ_IsActive { get; set; }
    }
}
