//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocationCostCodeMapping
    {
        public long CLC_Id { get; set; }
        public long CLC_CMP_Id { get; set; }
        public long CLC_CLM_Id { get; set; }
        public System.DateTime CLC_Date { get; set; }
        public string CLC_IsActive { get; set; }
    
        public virtual CostCodeLocationMapping CostCodeLocationMapping { get; set; }
    }
}
