//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfidentialityAgreement
    {
        public long CDA_Id { get; set; }
        public string CDA_EMP_EmployeeID { get; set; }
        public Nullable<System.DateTime> CDA_Date { get; set; }
        public string CDA_IsActive { get; set; }
    }
}
