//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLocationAllocation
    {
        public long CLA_Id { get; set; }
        public long CLA_CNT_Id { get; set; }
        public long CLA_LocationId { get; set; }
        public Nullable<decimal> CLA_Allocation { get; set; }
        public string CLA_IsActive { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
