//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCodeMaster
    {
        public CostCodeMaster()
        {
            this.CostCodes = new HashSet<CostCode>();
            this.LogCostCodes = new HashSet<LogCostCode>();
            this.LogCostCodeMasters = new HashSet<LogCostCodeMaster>();
            this.CostCodeLocationMappings = new HashSet<CostCodeLocationMapping>();
        }
    
        public long CCM_CostCode { get; set; }
        public string CCM_Description { get; set; }
        public string CCM_IsActive { get; set; }
        public long CCM_QBKId { get; set; }
    
        public virtual ICollection<CostCode> CostCodes { get; set; }
        public virtual ICollection<LogCostCode> LogCostCodes { get; set; }
        public virtual ICollection<LogCostCodeMaster> LogCostCodeMasters { get; set; }
        public virtual ICollection<CostCodeLocationMapping> CostCodeLocationMappings { get; set; }
    }
}
