//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectReportDetail
    {
        public long DefectID { get; set; }
        public long VehicleID { get; set; }
        public long WorkRequestAssignmentID { get; set; }
        public string VehicleNumber { get; set; }
        public string QRCodeID { get; set; }
        public string Status { get; set; }
        public string DefectType { get; set; }
        public string InspectionType { get; set; }
        public string DamageFile { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual eFleetVehicle eFleetVehicle { get; set; }
        public virtual WorkRequestAssignment WorkRequestAssignment { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
