//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectDepositForm
    {
        public long DDF_Id { get; set; }
        public string DDF_EMP_EmployeeID { get; set; }
        public string DDF_BankName_1 { get; set; }
        public string DDF_AccountType_1 { get; set; }
        public string DDF_AccountNumber_1 { get; set; }
        public string DDF_BankRoutingNumber_1 { get; set; }
        public Nullable<decimal> DDF_PrcentageOrDollarAmount_1 { get; set; }
        public string DDF_BankName_2 { get; set; }
        public string DDF_AccountType_2 { get; set; }
        public string DDF_AccountNumber_2 { get; set; }
        public string DDF_BankRoutingNumber_2 { get; set; }
        public string DDF_VoidCkeck { get; set; }
        public Nullable<System.DateTime> DDF_Date { get; set; }
        public string DDF_IsActive { get; set; }
    }
}
