//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eForm
    {
        public long EFM_Id { get; set; }
        public long EFM_MDL_Id { get; set; }
        public string EFM_eFormName { get; set; }
        public string EFM_eFormLink { get; set; }
        public Nullable<System.DateTime> EFM_Date { get; set; }
        public string EFM_IsActive { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
