//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContactForm
    {
        public long ECF_Id { get; set; }
        public string ECF_EMP_EmployeeID { get; set; }
        public string ECF_NickName { get; set; }
        public Nullable<long> ECF_HomePhone { get; set; }
        public string ECF_HomeEmail { get; set; }
        public Nullable<System.DateTime> ECF_Date { get; set; }
        public string ECF_IsActive { get; set; }
    }
}
