//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHandbook
    {
        public long EHB_Id { get; set; }
        public string EHB_EMP_EmployeeID { get; set; }
        public Nullable<System.DateTime> EHB_Date { get; set; }
        public string EHB_IsActive { get; set; }
    }
}
