//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectationEvaluation
    {
        public long EEL_Id { get; set; }
        public string EEL_EMP_EmployeeId { get; set; }
        public string EEL_EMP_EmployeeIdManager { get; set; }
        public Nullable<long> EEL_ASQ_Id { get; set; }
        public string EEL_QuestionType { get; set; }
        public string EEL_FinencialYear { get; set; }
        public string EEL_FinQuarter { get; set; }
        public string EEL_AnswerSelf { get; set; }
        public Nullable<decimal> EEL_ScoreSelf { get; set; }
        public string EEL_AnswerManager { get; set; }
        public Nullable<decimal> EEL_ScoreManager { get; set; }
        public string EEL_Comments { get; set; }
        public Nullable<System.DateTime> EEL_DateEval { get; set; }
        public Nullable<System.DateTime> EEL_Date { get; set; }
        public string EEL_IsActive { get; set; }
    }
}
