//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileType
    {
        public long FLT_Id { get; set; }
        public string FLT_FileType { get; set; }
        public string FLT_FileSubType { get; set; }
        public Nullable<System.DateTime> FLT_Date { get; set; }
        public string FLT_IsActive { get; set; }
    }
}
