//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormMaster
    {
        public long FRM_Id { get; set; }
        public string FRM_FormType { get; set; }
        public string FRM_FormName { get; set; }
        public string FRM_FormPath { get; set; }
        public string FRM_IsActive { get; set; }
    }
}
