//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdleEmployee
    {
        public long IdleId { get; set; }
        public Nullable<System.DateTime> IdleTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<long> IdleEmployeeId { get; set; }
        public string IsContinueIdle { get; set; }
        public Nullable<long> LocationId { get; set; }
    }
}
