//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewQuestion
    {
        public long INQ_Id { get; set; }
        public string INQ_QuestionType { get; set; }
        public string INQ_Question { get; set; }
        public string INQ_Exempt { get; set; }
        public Nullable<System.DateTime> INQ_Date { get; set; }
        public string INQ_IsActive { get; set; }
    }
}
