//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewSchedule
    {
        public long INS_Id { get; set; }
        public Nullable<long> INS_API_ApplicantId { get; set; }
        public string INS_EMP_InterviewerEmployeeId { get; set; }
        public string INS_IsHiringManager { get; set; }
        public string INS_IsAvailable { get; set; }
        public Nullable<System.DateTime> INS_AvailableTime { get; set; }
        public string INS_Comments { get; set; }
        public Nullable<System.DateTime> INS_InterviewDateTime { get; set; }
        public Nullable<System.DateTime> INS_Date { get; set; }
        public string INS_IsActive { get; set; }
    }
}
