//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewAnswer
    {
        public long INA_Id { get; set; }
        public Nullable<long> INA_IQC_Id { get; set; }
        public Nullable<long> INA_API_ApplicantId { get; set; }
        public string INA_EMP_EmployeeId { get; set; }
        public string INA_Answer { get; set; }
        public string INA_Comments { get; set; }
        public Nullable<System.DateTime> INA_Date { get; set; }
        public string INA_IsActive { get; set; }
    }
}
