//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> IsInvoiceDate { get; set; }
        public string OverrideCode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> InvoiceCriteria { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> WhomYou { get; set; }
        public Nullable<int> Business { get; set; }
        public Nullable<int> PuposeOfBilling { get; set; }
        public Nullable<int> FeeType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
