//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSettingMaster
    {
        public int Id { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<decimal> ParkerInvoicingCost { get; set; }
        public string StopParkingRegistration { get; set; }
        public Nullable<decimal> ParkeringRateIncreases { get; set; }
        public Nullable<System.DateTime> Transpireclosingprocesson { get; set; }
        public string InvoiceTemplate { get; set; }
        public string ReviewInvoiceBeforeSending { get; set; }
        public Nullable<System.DateTime> InvoicingDate { get; set; }
        public string Requestcollectionsemail { get; set; }
        public string AddBankAccount { get; set; }
        public string Settimefrequency { get; set; }
        public string frequencyautomaticrecons { get; set; }
        public Nullable<System.DateTime> SetClosingDate { get; set; }
        public string Frequencyinvoices { get; set; }
        public Nullable<System.DateTime> Automaticbillingdate { get; set; }
        public Nullable<System.DateTime> Cutoffcarddate { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
