//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationMaster()
        {
            this.AdminLocationMappings = new HashSet<AdminLocationMapping>();
            this.Bills = new HashSet<Bill>();
            this.BudgetLocationMappings = new HashSet<BudgetLocationMapping>();
            this.ContractLocationAllocations = new HashSet<ContractLocationAllocation>();
            this.CostCodeLocationMappings = new HashSet<CostCodeLocationMapping>();
            this.eFleetDrivers = new HashSet<eFleetDriver>();
            this.eFleetFuelings = new HashSet<eFleetFueling>();
            this.eFleetMaintenances = new HashSet<eFleetMaintenance>();
            this.eFleetPreventativeMaintenances = new HashSet<eFleetPreventativeMaintenance>();
            this.eFleetVehicleIncidents = new HashSet<eFleetVehicleIncident>();
            this.eFleetVehicleInspectionLogs = new HashSet<eFleetVehicleInspectionLog>();
            this.eFleetVehicleScanLogs = new HashSet<eFleetVehicleScanLog>();
            this.eFormTracks = new HashSet<eFormTrack>();
            this.EmailLogs = new HashSet<EmailLog>();
            this.EmployeeLocationMappings = new HashSet<EmployeeLocationMapping>();
            this.LocationClientMappings = new HashSet<LocationClientMapping>();
            this.LocationCompanyMappings = new HashSet<LocationCompanyMapping>();
            this.WorkRequestAssignments = new HashSet<WorkRequestAssignment>();
            this.LocationServices = new HashSet<LocationService>();
            this.LogBills = new HashSet<LogBill>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.LogLocationCompanyMappings = new HashSet<LogLocationCompanyMapping>();
            this.LogMiscellaneous = new HashSet<LogMiscellaneou>();
            this.LogPODetails = new HashSet<LogPODetail>();
            this.LogPODetailEmergencies = new HashSet<LogPODetailEmergency>();
            this.LogPreBills = new HashSet<LogPreBill>();
            this.ManagerLocationMappings = new HashSet<ManagerLocationMapping>();
            this.Miscellaneous = new HashSet<Miscellaneou>();
            this.PODetails = new HashSet<PODetail>();
            this.PODetailEmergencies = new HashSet<PODetailEmergency>();
            this.PreBills = new HashSet<PreBill>();
            this.QRCMasters = new HashSet<QRCMaster>();
            this.QRCScanLogs = new HashSet<QRCScanLog>();
            this.LoginLogs1 = new HashSet<LoginLog>();
        }
    
        public long LocationId { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Mobile { get; set; }
        public string PhoneNo { get; set; }
        public string ZipCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> QRCID { get; set; }
        public long LocationType { get; set; }
        public Nullable<long> LocationSubType { get; set; }
        public bool IsVerifiedByManager { get; set; }
        public bool IsVerifiedByClient { get; set; }
        public string LocationSubTypeDesc { get; set; }
        public Nullable<long> ContractHolder { get; set; }
        public Nullable<long> OperatingCompany { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<long> ContractType { get; set; }
        public string ClientInvoicingTerm { get; set; }
        public string ReportingType { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
        public Nullable<decimal> InterCompanyMgmFee { get; set; }
        public Nullable<System.DateTime> InterCompanyInvoicing { get; set; }
        public string ContractTerm { get; set; }
        public Nullable<bool> AdditionalYears { get; set; }
        public string Years { get; set; }
        public Nullable<long> QuickBookLocId { get; set; }
        public Nullable<int> PaymenttermsId { get; set; }
        public Nullable<System.DateTime> ClientInvoicingDate { get; set; }
        public Nullable<System.DateTime> Automaticbillingdate { get; set; }
        public Nullable<System.DateTime> Cutoffcarddate { get; set; }
        public Nullable<decimal> FrequencyOfInvoicing { get; set; }
        public Nullable<decimal> ChargeDepositeMonthlyParkerCard { get; set; }
        public Nullable<bool> IsChargeDepositeMonthlyParkerCard { get; set; }
        public Nullable<decimal> AviailableSpaces { get; set; }
        public Nullable<bool> IsSpecialRulesHourlyMan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminLocationMapping> AdminLocationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetLocationMapping> BudgetLocationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLocationAllocation> ContractLocationAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCodeLocationMapping> CostCodeLocationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetDriver> eFleetDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetFueling> eFleetFuelings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetMaintenance> eFleetMaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetPreventativeMaintenance> eFleetPreventativeMaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetVehicleIncident> eFleetVehicleIncidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetVehicleInspectionLog> eFleetVehicleInspectionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFleetVehicleScanLog> eFleetVehicleScanLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eFormTrack> eFormTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLocationMapping> EmployeeLocationMappings { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationClientMapping> LocationClientMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationCompanyMapping> LocationCompanyMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkRequestAssignment> WorkRequestAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationService> LocationServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBill> LogBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogLocationCompanyMapping> LogLocationCompanyMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogMiscellaneou> LogMiscellaneous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPODetail> LogPODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPODetailEmergency> LogPODetailEmergencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPreBill> LogPreBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerLocationMapping> ManagerLocationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miscellaneou> Miscellaneous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetailEmergency> PODetailEmergencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreBill> PreBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCMaster> QRCMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRCScanLog> QRCScanLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLogs1 { get; set; }
    }
}
