//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCostCode
    {
        public long LCCD_Id { get; set; }
        public long LCCD_CCD_CostCode { get; set; }
        public long LCCD_CCM_CostCode { get; set; }
        public string LCCD_Description { get; set; }
        public long LCCD_ModifiedBy { get; set; }
        public System.DateTime LCCD_ModifiedOn { get; set; }
        public Nullable<long> LCCD_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCCD_ApprovedOn { get; set; }
        public string LCCD_Comment { get; set; }
        public string LCCD_IsApprove { get; set; }
        public string LCCD_IsActive { get; set; }
        public string LCCD_Action { get; set; }
    
        public virtual CostCode CostCode { get; set; }
        public virtual CostCodeMaster CostCodeMaster { get; set; }
    }
}
