//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCompanyFacilityMapping
    {
        public long LCFM_Id { get; set; }
        public long LCFM_CFM_Id { get; set; }
        public long LCFM_CMP_Id { get; set; }
        public long LCFM_CCD_CostCode { get; set; }
        public string LCFM_FacilityType { get; set; }
        public string LCFM_Discription { get; set; }
        public Nullable<decimal> LCFM_Rate { get; set; }
        public Nullable<decimal> LCFM_Tax { get; set; }
        public System.DateTime LCFM_Date { get; set; }
        public long LCFM_ModifiedBy { get; set; }
        public System.DateTime LCFM_ModifiedOn { get; set; }
        public Nullable<long> LCFM_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCFM_ApprovedOn { get; set; }
        public string LCFM_Comment { get; set; }
        public string LCFM_IsApprove { get; set; }
        public string LCFM_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
