//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogContract
    {
        public long LCNT_Id { get; set; }
        public long LCNT_CNT_Id { get; set; }
        public long LCNT_CMP_IdFirsParty { get; set; }
        public long LCNT_CMP_IdSecondParty { get; set; }
        public long LCNT_CTT_Id { get; set; }
        public string LCNT_ExcutedBy { get; set; }
        public string LCNT_IssuedBy { get; set; }
        public long LCNT_PTM_Id { get; set; }
        public long LCNT_PMD_Id { get; set; }
        public Nullable<int> LCNT_GracePeriod { get; set; }
        public string LCNT_invoicingFrequency { get; set; }
        public Nullable<int> LCNT_CostDuringPeriod { get; set; }
        public Nullable<int> LCNT_AllocationNeeded { get; set; }
        public System.DateTime LCNT_StartDate { get; set; }
        public System.DateTime LCNT_EndDate { get; set; }
        public int LCNT_AnnualValueOfAggreement { get; set; }
        public Nullable<decimal> LCNT_MinimumBillAmount { get; set; }
        public Nullable<System.DateTime> LCNT_BillDueDate { get; set; }
        public Nullable<decimal> LCNT_LateFeeFine { get; set; }
        public string LCNT_ContractDocument { get; set; }
        public long LCNT_ModifiedBy { get; set; }
        public System.DateTime LCNT_ModifiedOn { get; set; }
        public Nullable<long> LCNT_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCNT_ApprovedOn { get; set; }
        public string LCNT_Comment { get; set; }
        public string LCNT_IsApprove { get; set; }
        public string LCNT_IsActive { get; set; }
        public string LCNT_IsReoccurring { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
    }
}
