//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCostCodeMaster
    {
        public long LCCM_Id { get; set; }
        public long LCCM_CCM_CostCode { get; set; }
        public string LCCM_Description { get; set; }
        public long LCCM_ModifiedBy { get; set; }
        public System.DateTime LCCM_ModifiedOn { get; set; }
        public Nullable<long> LCCM_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCCM_ApprovedOn { get; set; }
        public string LCCM_Comment { get; set; }
        public string LCCM_IsApprove { get; set; }
        public string LCCM_IsActive { get; set; }
        public string LCCM_Action { get; set; }
    
        public virtual CostCodeMaster CostCodeMaster { get; set; }
    }
}
