//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCompanyAccountDetail
    {
        public long LCAD_Id { get; set; }
        public long LCAD_CMP_Id { get; set; }
        public long LCAD_CAD_Id { get; set; }
        public long LCAD_PMD_Id { get; set; }
        public string LCAD_CardOrBankName { get; set; }
        public string LCAD_BankLocation { get; set; }
        public string LCAD_AccountNumber { get; set; }
        public string LCAD_CreditCardNumber { get; set; }
        public string LCAD_IFSCcode { get; set; }
        public string LCAD_SwiftBICcode { get; set; }
        public string LCAD_AccountDocument { get; set; }
        public long LCAD_ModifiedBy { get; set; }
        public System.DateTime LCAD_ModifiedOn { get; set; }
        public Nullable<long> LCAD_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCAD_ApprovedOn { get; set; }
        public string LCAD_Comment { get; set; }
        public string LCAD_IsApprove { get; set; }
        public string LCAD_IsActive { get; set; }
        public Nullable<decimal> LCAD_Balance { get; set; }
        public string LCAD_CardHolderName { get; set; }
        public Nullable<System.DateTime> LCAD_CardExpirationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyAccountDetail CompanyAccountDetail { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
