//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCompany
    {
        public long LCMP_Id { get; set; }
        public long LCMP_CMP_Id { get; set; }
        public string LCMP_NameLegal { get; set; }
        public string LCMP_NameDBA { get; set; }
        public Nullable<long> LCMP_VDT_Id { get; set; }
        public long LCMP_COT_Id { get; set; }
        public string LCMP_CompanyDocument { get; set; }
        public long LCMP_ModifiedBy { get; set; }
        public System.DateTime LCMP_ModifiedOn { get; set; }
        public Nullable<long> LCMP_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCMP_ApprovedOn { get; set; }
        public string LCMP_Comment { get; set; }
        public string LCMP_IsApprove { get; set; }
        public string LCMP_IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyType CompanyType { get; set; }
    }
}
