//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCompanyDetail
    {
        public long LCOD_Id { get; set; }
        public Nullable<long> LCOD_COD_Id { get; set; }
        public Nullable<long> LCOD_CMP_Id { get; set; }
        public string LCOD_PointOfContact { get; set; }
        public string LCOD_JobTitle { get; set; }
        public string LCOD_SSN { get; set; }
        public string LCOD_Address1 { get; set; }
        public string LCOD_Addr1City { get; set; }
        public Nullable<int> LCOD_Addr1StateId { get; set; }
        public Nullable<int> LCOD_Addr1CountryId { get; set; }
        public string LCOD_Address2 { get; set; }
        public string LCOD_Addr2City { get; set; }
        public Nullable<int> LCOD_Addr2StateId { get; set; }
        public Nullable<int> LCOD_Addr2CountryId { get; set; }
        public string LCOD_Phone1 { get; set; }
        public string LCOD_Phone2 { get; set; }
        public string LCOD_Email { get; set; }
        public string LCOD_Website { get; set; }
        public long LCOD_ModifiedBy { get; set; }
        public System.DateTime LCOD_ModifiedOn { get; set; }
        public Nullable<long> LCOD_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LCOD_ApprovedOn { get; set; }
        public string LCOD_Comment { get; set; }
        public string LCOD_IsApprove { get; set; }
        public string LCOD_IsActive { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual Company Company { get; set; }
    }
}
