//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFileUpload
    {
        public long LFLU_Id { get; set; }
        public string LFLU_FLU_FileId { get; set; }
        public string LFLU_Activity { get; set; }
        public string LFLU_AccessedBy { get; set; }
        public string LFLU_Comments { get; set; }
        public Nullable<System.DateTime> LFLU_Date { get; set; }
        public string LFLU_IsActive { get; set; }
    }
}
