//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLicense
    {
        public long LLNC_Id { get; set; }
        public long LLNC_LNC_Id { get; set; }
        public long LLNC_CMP_Id { get; set; }
        public string LLNC_LicenseName { get; set; }
        public string LLNC_Discription { get; set; }
        public string LLNC_LicenseNumber { get; set; }
        public System.DateTime LLNC_ExpirationDate { get; set; }
        public string LLNC_LicenseDocument { get; set; }
        public long LLNC_ModifiedBy { get; set; }
        public System.DateTime LLNC_ModifiedOn { get; set; }
        public Nullable<long> LLNC_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LLNC_ApprovedOn { get; set; }
        public string LLNC_Comment { get; set; }
        public string LLNC_IsApprove { get; set; }
        public string LLNC_IsActive { get; set; }
    
        public virtual License License { get; set; }
        public virtual Company Company { get; set; }
    }
}
