//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMiscellaneou
    {
        public long LMIS_Id { get; set; }
        public long LMIS_MIS_Id { get; set; }
        public Nullable<long> LMIS_CCD_CostCode { get; set; }
        public long LMIS_LocationId { get; set; }
        public Nullable<long> LMIS_CMP_Id { get; set; }
        public string LMIS_Discription { get; set; }
        public Nullable<decimal> LMIS_InvoiceAmount { get; set; }
        public Nullable<System.DateTime> LMIS_InvoiceDate { get; set; }
        public string LMIS_InvoiceDocument { get; set; }
        public long LMIS_ModifiedBy { get; set; }
        public System.DateTime LMIS_ModifiedOn { get; set; }
        public Nullable<long> LMIS_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LMIS_ApprovedOn { get; set; }
        public string LMIS_Comment { get; set; }
        public string LMIS_IsApprove { get; set; }
        public string LMIS_IsActive { get; set; }
    
        public virtual CostCode CostCode { get; set; }
        public virtual Company Company { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
