//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPODetail
    {
        public long LPOD_Id { get; set; }
        public long LPOD_POD_Id { get; set; }
        public long LPOD_LocationId { get; set; }
        public long LPOD_POT_Id { get; set; }
        public Nullable<long> LPOD_CMP_Id { get; set; }
        public Nullable<System.DateTime> LPOD_DeliveryDate { get; set; }
        public Nullable<System.DateTime> LPOD_PODate { get; set; }
        public Nullable<decimal> LPOD_POAmount { get; set; }
        public Nullable<System.DateTime> LPOD_ReoccourringBillDate { get; set; }
        public string LPOD_EmergencyPODocument { get; set; }
        public long LPOD_ModifiedBy { get; set; }
        public System.DateTime LPOD_ModifiedOn { get; set; }
        public Nullable<long> LPOD_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LPOD_ApprovedOn { get; set; }
        public string LPOD_Comment { get; set; }
        public string LPOD_IsApprove { get; set; }
        public string LPOD_IsActive { get; set; }
        public Nullable<long> LPOD_RUL_Id { get; set; }
        public string LPOD_RUL_Level { get; set; }
        public string LPOD_RUL_CurrentLevel { get; set; }
        public Nullable<System.DateTime> LPOD_POD_ReccuringDate { get; set; }
        public string LPOD_POD_ReccuringStatus { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual PODetail PODetail { get; set; }
        public virtual POType POType { get; set; }
    }
}
