//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPODetailEmergency
    {
        public long LPOE_Id { get; set; }
        public long LPOE_POE_Id { get; set; }
        public long LPOE_LocationId { get; set; }
        public long LPOE_POT_Id { get; set; }
        public string LPOE_VendorName { get; set; }
        public string LPOE_EmergencyComment { get; set; }
        public decimal LPOE_POAmount { get; set; }
        public Nullable<System.DateTime> LPOE_PODate { get; set; }
        public string LPOE_EmergencyPODocument { get; set; }
        public long LPOE_ModifiedBy { get; set; }
        public System.DateTime LPOE_ModifiedOn { get; set; }
        public Nullable<long> LPOE_ApprovedBy { get; set; }
        public Nullable<System.DateTime> LPOE_ApprovedOn { get; set; }
        public string LPOE_Comment { get; set; }
        public string LPOE_IsApprove { get; set; }
        public string LPOE_IsActive { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual PODetailEmergency PODetailEmergency { get; set; }
        public virtual POType POType { get; set; }
    }
}
