//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NTF_Id { get; set; }
        public string NTF_Details { get; set; }
        public string NTF_Module { get; set; }
        public string NTF_Submodule { get; set; }
        public string NTF_SubmoduleId { get; set; }
        public string NTF_AssignTo { get; set; }
        public Nullable<bool> NTF_AssignToIsWorkable { get; set; }
        public Nullable<bool> NTF_IsRead { get; set; }
        public Nullable<System.DateTime> NTF_DeletedDate { get; set; }
        public string NTF_CreatedBy { get; set; }
        public Nullable<bool> NTF_CreatedByIsWorkable { get; set; }
        public string NFT_Severity { get; set; }
        public Nullable<System.DateTime> NTF_CreatedDate { get; set; }
        public string NTF_IsActive { get; set; }
    }
}
