//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDetail
    {
        public long NID { get; set; }
        public Nullable<long> ModuleId { get; set; }
        public Nullable<long> AssignUserId { get; set; }
        public Nullable<long> WorkOrderID { get; set; }
        public Nullable<long> eFleetID { get; set; }
        public Nullable<long> POID { get; set; }
        public Nullable<long> MiscellaneousID { get; set; }
        public Nullable<long> BillID { get; set; }
        public Nullable<long> eScanId { get; set; }
        public bool IsRead { get; set; }
        public Nullable<long> ReadBy { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
