//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoReleaseForm
    {
        public long PRF_Id { get; set; }
        public string PRF_EMP_EmployeeID { get; set; }
        public Nullable<System.DateTime> PRF_Date { get; set; }
        public string PRF_IsActive { get; set; }
    }
}
