//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POFacilityItem
    {
        public long POF_Id { get; set; }
        public long POF_POD_Id { get; set; }
        public long POF_CFM_Id { get; set; }
        public Nullable<long> POF_Unit { get; set; }
        public string POF_IsActive { get; set; }
    
        public virtual PODetail PODetail { get; set; }
    }
}
