//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POType
    {
        public POType()
        {
            this.LogPODetails = new HashSet<LogPODetail>();
            this.PODetails = new HashSet<PODetail>();
        }
    
        public long POT_Id { get; set; }
        public string POT_POType { get; set; }
        public string POT_IsActive { get; set; }
    
        public virtual ICollection<LogPODetail> LogPODetails { get; set; }
        public virtual ICollection<PODetail> PODetails { get; set; }
    }
}
