//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public long RQS_Id { get; set; }
        public string RQS_RequizationType { get; set; }
        public long RQS_ActivityId { get; set; }
        public string RQS_ActionStatus { get; set; }
        public Nullable<int> RQS_HeadCount { get; set; }
        public string RQS_CreatedBy { get; set; }
        public Nullable<System.DateTime> RQS_CreatedDate { get; set; }
        public string RQS_ApprovedBy { get; set; }
        public Nullable<System.DateTime> RQS_ApprovedDate { get; set; }
        public string RQS_ApprovalStatus { get; set; }
        public string RQS_ApprovalComment { get; set; }
        public Nullable<System.DateTime> RQS_Date { get; set; }
        public string RQS_IsActive { get; set; }
    }
}
