//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_MeetingSchedule
    {
        public long RMS_Id { get; set; }
        public string RMS_EMP_EmployeeId { get; set; }
        public string RMS_FinencialYear { get; set; }
        public string RMS_FinQuarter { get; set; }
        public Nullable<System.DateTime> RMS_InterviewDateTime { get; set; }
        public Nullable<System.DateTime> RMS_Date { get; set; }
        public string RMS_IsActive { get; set; }
    }
}
