//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public long RUL_Id { get; set; }
        public long RUL_MDL_Id { get; set; }
        public string RUL_RuleName { get; set; }
        public string RUL_Level { get; set; }
        public Nullable<decimal> RUL_SlabFrom { get; set; }
        public Nullable<decimal> RUL_SlabTo { get; set; }
        public Nullable<long> RUL_ByPass_UserId { get; set; }
        public string RUL_ByPassLevel { get; set; }
        public Nullable<System.DateTime> RUL_Date { get; set; }
        public string RUL_IsActive { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
