//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAssessmentReview306090
    {
        public long SAR_Id { get; set; }
        public string SAR_EMP_EmployeeId { get; set; }
        public string SAR_EMP_EmployeeIdManager { get; set; }
        public Nullable<long> SAR_ASQ_Id { get; set; }
        public string SAR_QuestionType { get; set; }
        public string SAR_AnswerSelf { get; set; }
        public string SAR_AnswerManager { get; set; }
        public string SAR_Comments { get; set; }
        public Nullable<System.DateTime> SAR_DateReview { get; set; }
        public Nullable<System.DateTime> SAR_Date { get; set; }
        public string SAR_IsActive { get; set; }
    }
}
