//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfAssessment306090
    {
        public long SAM_Id { get; set; }
        public string SAM_EMP_EmployeeId { get; set; }
        public Nullable<long> SAM_ASQ_Id { get; set; }
        public string SAM_Answer { get; set; }
        public Nullable<System.DateTime> SAM_Date { get; set; }
        public string SAM_IsActive { get; set; }
    }
}
