//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotTime
    {
        public long SLT_Id { get; set; }
        public System.TimeSpan SLT_fromTime { get; set; }
        public System.TimeSpan SLT_ToTime { get; set; }
        public Nullable<System.DateTime> SLT_Date { get; set; }
        public string SLT_IsActive { get; set; }
    }
}
