//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetLicense_Result1
    {
        public long LNC_Id { get; set; }
        public long LNC_CMP_Id { get; set; }
        public string LNC_LicenseName { get; set; }
        public string LNC_LicenseNumber { get; set; }
        public System.DateTime LNC_ExpirationDate { get; set; }
        public string LNC_LicenseDocument { get; set; }
        public string Status { get; set; }
    }
}
