//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetDepartment_Result1
    {
        public long DPT_Id { get; set; }
        public string DPT_Name { get; set; }
        public Nullable<System.DateTime> DPT_Date { get; set; }
        public string DPT_IsActive { get; set; }
    }
}
