//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetAssessmentQuestion_Result2
    {
        public long ASQ_Id { get; set; }
        public string ASQ_AssessmentType { get; set; }
        public string ASQ_QuestionType { get; set; }
        public string ASQ_Question { get; set; }
        public string SAM_Id { get; set; }
        public string SAM_Answer { get; set; }
    }
}
