//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetFileUpload_Result1
    {
        public long FLU_FileId { get; set; }
        public long FLU_FLT_Id { get; set; }
        public string FLT_FileType { get; set; }
        public string FLU_EMP_EmployeeId { get; set; }
        public string FLU_FileName { get; set; }
        public string FLU_FileAttached { get; set; }
        public string FLU_FileUploadedBy { get; set; }
        public Nullable<System.DateTime> FLU_Date { get; set; }
        public string FLU_IsActive { get; set; }
    }
}
