//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetFormRateOfPay_Result2
    {
        public string JBT_JobTitle { get; set; }
        public string EmployeeName { get; set; }
        public string HiringManager { get; set; }
        public string Operation { get; set; }
        public string LocationName { get; set; }
        public string VST_EmploymentStatus { get; set; }
        public string VST_IsExempt { get; set; }
        public Nullable<decimal> VST_RateOfPay { get; set; }
        public string TypeOfPayChange { get; set; }
    }
}
