//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetJobPosting_Result7
    {
        public long JPS_JobPostingId { get; set; }
        public Nullable<long> JBT_Id { get; set; }
        public string JPS_HiringManagerID { get; set; }
        public Nullable<long> JPS_LocationId { get; set; }
        public string LocationName { get; set; }
        public string JobTitle { get; set; }
        public string VST_JobDescription { get; set; }
        public Nullable<int> PositionCount { get; set; }
        public string VST_IsExempt { get; set; }
        public Nullable<int> ApplicantCount { get; set; }
        public string JobPostingDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Status { get; set; }
    }
}
