//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetCompanyListForAdmin_Result2
    {
        public long CMP_Id { get; set; }
        public string CMP_NameLegal { get; set; }
        public Nullable<long> COT_Id { get; set; }
        public string COT_CompanyType { get; set; }
        public string TXD_TaxIdNumber { get; set; }
        public string LNC_LicenseDocument { get; set; }
        public Nullable<System.DateTime> LNC_ExpirationDate { get; set; }
        public string Address1 { get; set; }
        public string COD_Phone1 { get; set; }
        public string Status { get; set; }
    }
}
