//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetCostCodeLocationMapping_Result8
    {
        public long CCM_CostCode { get; set; }
        public string CCM_Description { get; set; }
        public string CCM_IsActive { get; set; }
    }
}
