//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetVehicleSeating_Result1
    {
        public long VST_Id { get; set; }
        public string VST_Title { get; set; }
        public string VST_JobDescription { get; set; }
        public string VST_RolesAndResponsiblities { get; set; }
        public string VST_Level { get; set; }
        public long VST_ParentId { get; set; }
        public Nullable<long> DPT_Id { get; set; }
        public string DPT_Name { get; set; }
        public string VST_EmploymentStatus { get; set; }
        public string VST_IsExempt { get; set; }
        public Nullable<decimal> VST_RateOfPay { get; set; }
    }
}
