//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGeteFormTrack_Result1
    {
        public long EFT_Id { get; set; }
        public long EFT_MDL_Id { get; set; }
        public long EFT_EFM_Id { get; set; }
        public long EFT_LocationId { get; set; }
        public long EFT_ModifiedBy { get; set; }
        public Nullable<long> EFT_ApprovedBy { get; set; }
        public string EFT_eFormTrackLink { get; set; }
        public string EFT_Comment { get; set; }
        public Nullable<System.DateTime> EFT_ApprovedOn { get; set; }
        public Nullable<System.DateTime> EFT_ApprovedOn1 { get; set; }
        public string EFT_IsActive { get; set; }
        public string MDL_ModuleName { get; set; }
        public string EFM_eFormName { get; set; }
        public string LocationName { get; set; }
        public string NameModifiedBy { get; set; }
        public string NameApprovedBy { get; set; }
    }
}
