//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetRule_Result1
    {
        public long RUL_Id { get; set; }
        public long RUL_MDL_Id { get; set; }
        public string MDL_ModuleName { get; set; }
        public string RUL_RuleName { get; set; }
        public string RUL_Level { get; set; }
        public Nullable<decimal> RUL_SlabFrom { get; set; }
        public Nullable<decimal> RUL_SlabTo { get; set; }
        public long RUL_ByPass_UserId { get; set; }
        public long RUL_ByPass_UserId1 { get; set; }
        public Nullable<System.DateTime> RUL_Date { get; set; }
        public string RUL_IsActive { get; set; }
    }
}
