//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetMiscellaneousDetail_Result3
    {
        public long LMIS_Id { get; set; }
        public long LMIS_MIS_Id { get; set; }
        public string LocationName { get; set; }
        public string CMP_NameLegal { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<decimal> MISAmount { get; set; }
        public string MISDate { get; set; }
        public string LMIS_InvoiceDocument { get; set; }
        public string LMIS_Comment { get; set; }
        public string Status { get; set; }
    }
}
