//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetVehicleSeating_DepartmentMapping_Result1
    {
        public long VDM_Id { get; set; }
        public long VDM_VST_Id { get; set; }
        public long VDM_DPT_Id { get; set; }
        public string VDM_IsActive { get; set; }
    }
}
