//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetEmergencyContactForm_Result3
    {
        public long ECF_Id { get; set; }
        public string ECF_EMP_EmployeeID { get; set; }
        public string ECF_FirstName { get; set; }
        public string ECF_MiddleName { get; set; }
        public string ECF_LastName { get; set; }
        public string ECF_Gender { get; set; }
        public string ECF_Citizenship { get; set; }
        public string ECF_HomeAddress { get; set; }
        public Nullable<long> ECF_Mobile { get; set; }
        public Nullable<System.DateTime> ECF_BirthDate { get; set; }
        public byte[] ECF_SSN { get; set; }
        public string ECF_DriverLicense { get; set; }
        public string ECF_NickName { get; set; }
        public Nullable<long> ECF_HomePhone { get; set; }
        public string ECF_HomeEmail { get; set; }
        public string ECF_EmergencyContactName { get; set; }
        public string ECF_Relationship { get; set; }
        public string ECF_Address { get; set; }
        public Nullable<long> ECF_PhoneNumber { get; set; }
        public Nullable<System.DateTime> ECF_Date { get; set; }
        public string ECF_IsActive { get; set; }
    }
}
