//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetCompanyList_Result2
    {
        public long CMP_Id { get; set; }
        public string CMP_NameLegal { get; set; }
        public string VDT_VendorType { get; set; }
        public string COD_PointOfContact { get; set; }
        public string Address1 { get; set; }
        public string COD_Phone1 { get; set; }
        public string Status { get; set; }
    }
}
