//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetEmployeeManagementList_Result1
    {
        public string EMP_EmployeeID { get; set; }
        public string EMP_Photo { get; set; }
        public string EmployeeName { get; set; }
        public string EMP_Email { get; set; }
        public string DepartmentName { get; set; }
        public string JBT_JobTitle { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.DateTime> EMP_DateOfJoining { get; set; }
        public string VST_Level { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
