//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetEmergencyContactForm_Result2
    {
        public long ECF_Id { get; set; }
        public string ECF_EMP_EmployeeID { get; set; }
        public string ECF_NickName { get; set; }
        public Nullable<long> ECF_HomePhone { get; set; }
        public string ECF_HomeEmail { get; set; }
    }
}
