//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetApprovedBillList_Result1
    {
        public long LBLL_Id { get; set; }
        public Nullable<long> LBLL_BLL_Id { get; set; }
        public string CMP_NameLegal { get; set; }
        public string LocationName { get; set; }
        public string LBLL_BillType { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public System.DateTime BillDate { get; set; }
        public Nullable<int> Delay_Days { get; set; }
    }
}
