//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetPIP_Termination_CorrectiveAction_Result1
    {
        public string type { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EMP_Photo { get; set; }
        public string JBT_JobTitle { get; set; }
        public string TStatus { get; set; }
    }
}
