//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    
    public partial class spGetPODetail_Result8
    {
        public Nullable<long> POD_Id { get; set; }
        public Nullable<long> POD_LocationId { get; set; }
        public Nullable<long> POD_POT_Id { get; set; }
        public Nullable<long> POD_CMP_Id { get; set; }
        public Nullable<System.DateTime> POD_DeliveryDate { get; set; }
        public string POD_EmergencyPODocument { get; set; }
        public Nullable<System.DateTime> POD_PODate { get; set; }
        public Nullable<System.DateTime> POD_ReoccourringBillDate { get; set; }
        public string POD_IsActive { get; set; }
        public string CNT_invoicingFrequency { get; set; }
        public Nullable<int> CNT_CostDuringPeriod { get; set; }
        public Nullable<decimal> CNT_AnnualValueOfAggreement { get; set; }
        public string POE_VendorName { get; set; }
        public string POE_EmergencyComment { get; set; }
        public Nullable<decimal> POE_POAmount { get; set; }
        public string COD_PointOfContact { get; set; }
        public string COD_Address { get; set; }
        public Nullable<decimal> POD_POAmount { get; set; }
        public string LocationName { get; set; }
        public string CMP_NameLegal { get; set; }
        public string POT_POType { get; set; }
    }
}
