//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxDetail()
        {
            this.LogTaxDetails = new HashSet<LogTaxDetail>();
        }
    
        public long TXD_Id { get; set; }
        public long TXD_CMP_Id { get; set; }
        public string TXD_TaxIdNumber { get; set; }
        public string TXD_TaxDocument { get; set; }
        public string TXD_IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTaxDetail> LogTaxDetails { get; set; }
    }
}
