//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Client_Invoice_Receive_Payment
    {
        public long Id { get; set; }
        public Nullable<long> TCI_ID { get; set; }
        public Nullable<System.DateTime> PaymentReceiveDate { get; set; }
        public Nullable<long> PaymentMethod { get; set; }
        public string ReferenceCheckNo { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string DepositStatus { get; set; }
        public string DepositAccount { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<System.DateTime> EstimatedDepositDate { get; set; }
        public Nullable<long> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryOn { get; set; }
    
        public virtual Tbl_Client_Invoice Tbl_Client_Invoice { get; set; }
    }
}
