//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Log_Customer_Vehicle_Details
    {
        public long Id { get; set; }
        public Nullable<long> TCVD_Id { get; set; }
        public Nullable<long> CMP_Id { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string LicensePlateNo { get; set; }
        public Nullable<int> State { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Comment { get; set; }
        public string IsApprove { get; set; }
        public string IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Tbl_Customer_Vehicle_Details Tbl_Customer_Vehicle_Details { get; set; }
    }
}
