//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LeaveType_Setup
    {
        public int TypeId { get; set; }
        public string LeaveDesc { get; set; }
        public Nullable<decimal> LeaveCount { get; set; }
        public string LeaveYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCarryForward { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
