//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Client_Draft_Invoice_Item_Details
    {
        public long Id { get; set; }
        public Nullable<long> TCDI_Id { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<long> CategoryType { get; set; }
        public Nullable<long> RevenueCode { get; set; }
        public Nullable<decimal> ItemUnitCost { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Tbl_Client_Draft_Invoice Tbl_Client_Draft_Invoice { get; set; }
    }
}
