//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Staffing_Addition
    {
        public long EventId { get; set; }
        public Nullable<bool> IsHCTS { get; set; }
        public Nullable<bool> IsSTS { get; set; }
        public Nullable<bool> IsAutoSchedule { get; set; }
        public Nullable<long> Location { get; set; }
        public Nullable<long> UserLocation { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    }
}
