//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HRMS_Holiday
    {
        public int Id { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public string HolidayName { get; set; }
        public string Description { get; set; }
        public string FinYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> HolidayType { get; set; }
    }
}
