
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkOrderEMS.Data.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_DOT_Management_HDR
{

    public int Id { get; set; }

    public string NameofCompanyApplying { get; set; }

    public string CompanyID { get; set; }

    public Nullable<System.DateTime> TodayDate { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public Nullable<int> ZipPostCode { get; set; }

    public Nullable<int> Email { get; set; }

    public string HomeTelephone { get; set; }

    public string IDNumber { get; set; }

    public Nullable<System.DateTime> ExpirationDate { get; set; }

    public string EntryBy { get; set; }

    public Nullable<System.DateTime> EntryDate { get; set; }

    public string UpdateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

}

}
