//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminationForm
    {
        public long TMN_Id { get; set; }
        public string TMN_EmployeeId { get; set; }
        public Nullable<long> TMN_ManagerId { get; set; }
        public Nullable<System.DateTime> TMN_HRTerminationDate { get; set; }
        public Nullable<System.DateTime> TMN_LastWorkingDay { get; set; }
        public string TMN_TerminationReason { get; set; }
        public string TMN_TerminationDiscription { get; set; }
        public string TMN_RehireRecommended { get; set; }
        public string TMN_HRApproal { get; set; }
        public string TMN_IsSeverance { get; set; }
        public Nullable<int> TMN_LengthOfSeverance { get; set; }
        public string TMN_SeveranceApproval { get; set; }
        public Nullable<long> TMN_WitnessId { get; set; }
        public Nullable<System.DateTime> TMN_Date { get; set; }
        public string TMN_IsActive { get; set; }
        public string TMN_HRDenyReason { get; set; }
        public string TMN_HRDenyComment { get; set; }
    }
}
