//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOverrideUsertype
    {
        public long UOU_Id { get; set; }
        public long UOU_UserId { get; set; }
        public long UOU_SMD_Id { get; set; }
        public Nullable<long> UOU_OverrideUserTypeId { get; set; }
        public Nullable<System.DateTime> UOU_Date { get; set; }
        public string UOU_IsActive { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual SubModule SubModule { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
