//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSeatingSubModuleMapping
    {
        public long VSM_Id { get; set; }
        public long VSM_VST_Id { get; set; }
        public long VSM_SMD_Id { get; set; }
        public long VSM_UserTypeId { get; set; }
        public Nullable<System.DateTime> VSM_Date { get; set; }
        public string VSM_IsActive { get; set; }
    
        public virtual SubModule SubModule { get; set; }
    }
}
