//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorType
    {
        public VendorType()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public long VDT_Id { get; set; }
        public string VDT_VendorType { get; set; }
        public string VDT_IsActive { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
}
