//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USERTYPE
    {
        public long GlobalCodeId { get; set; }
        public string Category { get; set; }
        public string CodeName { get; set; }
        public bool IsActive { get; set; }
    }
}
