//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class W4Form
    {
        public long W4F_Id { get; set; }
        public string W4F_EMP_EmployeeId { get; set; }
        public string W4F_SSN { get; set; }
        public string W4F_3MaritalStatus { get; set; }
        public string W4F_4 { get; set; }
        public Nullable<int> W4F_5 { get; set; }
        public Nullable<decimal> W4F_6 { get; set; }
        public Nullable<decimal> W4F_7 { get; set; }
        public string W4F_8EmployersName { get; set; }
        public Nullable<System.DateTime> W4F_9 { get; set; }
        public string W4F_10 { get; set; }
        public Nullable<System.DateTime> W4F_Date { get; set; }
        public string W4F_IsActive { get; set; }
    }
}
