//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Witness
    {
        public long WTS_Id { get; set; }
        public Nullable<long> WTS_TMN_Id { get; set; }
        public string WTS_IsEliteEmployee { get; set; }
        public string WTS_WitnessName { get; set; }
        public string WTS_Position { get; set; }
        public Nullable<long> WTS_LocationId { get; set; }
        public string WTS_CompanyTheyWorkFor { get; set; }
        public Nullable<System.DateTime> WTS_Date { get; set; }
        public string WTS_IsActive { get; set; }
    }
}
